// manual-tests/mockOrderData.js

export const mockOrderData1 = {
	'issues': {
		'epicId': 'BMGMN-9196',
		'projectStoryId': 'BMGMN-9197',
		'designStoryId': 'BMGMN-9198',
		'networkStoryId': 'BMGMN-9199',
		'codecStoryId': 'BMGMN-9200'
	},
	'userId': '6697d8c836bf4bae831e8bc8',
	'status': 'awaiting:feasibility',
	'expiresAt': '2025-01-24T23:42:56.311Z',
	'serviceOrder': {
		'userId': '6697d8c836bf4bae831e8bc8',
		'userName': 'Chinmaya Balakrishna',
		'status': 'confirmed',
		'network': 'G',
		'projectName': 'Resources Project Name 191',
		'remarks': 'Brief description about this order - Resources Project Name 191',
		'handoverDate': '31/Dec/2024',
		'supportingDocs': [
			{
				'path': '1 - FIFA WWC 23 - Media data.pdf',
				'preview': 'blob:https://portal.gmn.media.aws.cloud.in.company.com.au/7fd5d9af-f522-45f9-82ab-e3417757b015'
			}
		],
		'supportingExcels': [
			{
				'path': 'Laver Cup Berlin 2024 v2.1 3 services.xlsm',
				'preview': 'blob:https://portal.gmn.media.aws.cloud.in.company.com.au/94621bab-7b69-4eda-931f-9d0a77f78144'
			}
		],
		'orderType': 'MOT',
		'customerName': 'TGL',
		'cidn': '15768',
		'aSiteName': 'Core',
		'aEndAddress': 'Core',
		'currentStageCode': 'DSAL',
		'serviceType': 'HD',
		'country': 'AUS',
		'bSiteName': 'GDIH',
		'bEndAddress': 'BARRYST',
		'services': [
			{
				'sourceCountry': 'AUS',
				'sourceSite': 'GDIH',
				'sourceSiteDesc': 'BARRYST',
				'farCountry': '',
				'farSite': '',
				'farSiteDesc': '',
				'resource': 'Port',
				'requestType': 'newServiceToPort',
				'workRequired': 'VIP (NATFW)',
				'chassis': 'TGL-GDIH-A1105-1A',
				'path': 'A',
				'slot': 'MS 5',
				'slotId': '1752871',
				'slotName': 'TGL-GDIH-A1105-1A-MS 5',
				'card': 'SDMP-4S-Q40',
				'cardStatus': 'PLANNED',
				'newCardStatus': '701',
				'cardStatusDescription': 'Planned',
				'newCardStatusDescription': 'Planned',
				'cardProjectNumber': 'FY22BARRYST',
				'cardNewProjectNumber': '',
				'defaultApp': 'aperi-app-natfw-1g',
				'newDefaultApp': '',
				'cardHandOff': 'Unassigned',
				'newCardHandOff': '',
				'cardHandOffDescription': 'Unassigned',
				'newCardHandOffDescription': '',
				'pinOut': 'D',
				'newPinOut': '',
				'pinOutDescription': 'Data Centre Interconnect',
				'newPinOutDescription': '',
				'port': 'TGL-GDIH-A1105-1A.5.4.H.VIP',
				'portId': '801013',
				'portStatus': 'PLANNED',
				'newPortStatus': 'PLANNED',
				'portStatusDescription': 'Planned',
				'newPortStatusDescription': 'Planned',
				'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP',
				'friendlyName': 'BARRYST AP VIP-1A.5.4.H',
				'portNo': '7',
				'portProjectNumber': 'TestProjectNATFW02',
				'portNewProjectNumber': '',
				'TxFlows': 2,
				'RxFlows': 2,
				'vipBlock': 0,
				'newVIPBlock': 48,
				'phyInterfaceType': '825',
				'newPhyInterfaceType': '826',
				'serviceType': 'VIP (NATFW)',
				'newServiceType': 'VIP (NATFW)',
				'handOff': '',
				'newHandOff': 'H',
				'handOffDescription': '',
				'newHandOffDescription': 'Hitless',
				'serviceUse': 'I',
				'newServiceUse': 'P',
				'serviceUseDescription': 'Itinerant',
				'newServiceUseDescription': 'Permanent',
				'gmnInterfaceType': 'VIP',
				'newGMNInterfaceType': 'VIP',
				'detailedVIPFlows': [
					{
						'id': '123',
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX1',
						'status': 'Modified',
						'flowNo': '1',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX1',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX1',
						'primaryIp': '10.12.20.79',
						'primaryMulticastIp': '225.12.20.79',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.79',
						'secondaryMulticastIp': '225.212.21.79',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestingPorta2002',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'CHANGE',
						'customerVlan': '3100',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '1.1.1.12',
						'customerGateway': '1.1.1.15',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '2100',
						'mediaFlowDestPort': '2200',
						'mediaFlowSsrc': 'v3',
						'mediaFlowProtocol': 'TEST',
						'mediaFlowHitlessMode': 'Hitless',
						'mediaFlowMbps': '55'
					},
					{
						'id': '1234',
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX2',
						'status': 'Modified',
						'flowNo': '2',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX2',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX2',
						'primaryIp': '10.12.20.80',
						'primaryMulticastIp': '225.12.20.80',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.80',
						'secondaryMulticastIp': '225.212.21.80',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestProjectNATFW02',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'CHANGE',
						'customerVlan': '3100',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '1.1.1.12',
						'customerGateway': '1.1.1.15',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '2100',
						'mediaFlowDestPort': '2200',
						'mediaFlowSsrc': 'v3',
						'mediaFlowProtocol': 'TEST',
						'mediaFlowHitlessMode': 'Hitless',
						'mediaFlowMbps': '55'
					},
					{
						'id': '12345',
						'name': 'TGL-GDIH-A1105-1A.5.4.A.VIP.RX2',
						'status': 'Deleted',
						'flowNo': '2',
						'TxRx': 'RX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP.RX2',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.RX2',
						'primaryIp': '10.12.20.80',
						'primaryMulticastIp': '225.12.20.80',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.80',
						'secondaryMulticastIp': '225.212.21.80',
						'secondaryVlan': '29',
						'flowProjectNumber': 'Testing21Dec2023',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': '',
						'requestType': 'NEW',
						'customerVlan': '',
						'customerVideoIp': '',
						'customerNetmask': '',
						'customerGateway': '',
						'customerIgmpVersion': '',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': ''
					},
					{
						'id': '123456',
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX3',
						'flowNo': '3',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX3',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX3',
						'primaryIp': '10.12.20.81',
						'primaryMulticastIp': '225.12.20.81',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.81',
						'secondaryMulticastIp': '225.212.21.81',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestProjectNATFW02',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'NEW',
						'customerVlan': '',
						'customerVideoIp': '',
						'customerNetmask': '',
						'customerGateway': '',
						'customerIgmpVersion': '',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': ''
					}
				]
			},
			{
				'sourceCountry': 'AUS',
				'sourceSite': 'GDIH',
				'sourceSiteDesc': 'BARRYST',
				'farCountry': '',
				'farSite': '',
				'farSiteDesc': '',
				'resource': 'Port',
				'requestType': 'newServiceToPort',
				'workRequired': 'VIP (NATFW)',
				'chassis': 'TGL-GDIH-A1105-1B',
				'path': 'B',
				'slot': 'MS 2',
				'slotId': '1751094',
				'slotName': 'TGL-GDIH-A1105-1B-MS 2',
				'card': 'SDMP-4S-Q40',
				'cardStatus': 'PLANNED',
				'newCardStatus': '701',
				'cardStatusDescription': 'Planned',
				'newCardStatusDescription': 'Planned',
				'cardProjectNumber': 'FY22BARRYST',
				'cardNewProjectNumber': '',
				'defaultApp': 'Unassigned',
				'newDefaultApp': '',
				'cardHandOff': 'Unassigned',
				'newCardHandOff': '',
				'cardHandOffDescription': 'Unassigned',
				'newCardHandOffDescription': '',
				'pinOut': 'Unassigned',
				'newPinOut': '',
				'pinOutDescription': 'Unassigned',
				'newPinOutDescription': '',
				'port': 'TGL-GDIH-A1105-1B.2.4.B.VIP',
				'portId': '800925',
				'portStatus': 'PLANNED',
				'newPortStatus': 'PLANNED',
				'portStatusDescription': 'Planned',
				'newPortStatusDescription': 'Planned',
				'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP',
				'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4',
				'portNo': '7',
				'portProjectNumber': 'FY22BARRYST',
				'portNewProjectNumber': '',
				'TxFlows': '5',
				'RxFlows': '5',
				'vipBlock': '24',
				'newVIPBlock': '48',
				'serviceType': 'VIP (NATFW)',
				'newServiceType': 'VIP (NATFW)',
				'handOff': 'Unassigned',
				'newHandOff': 'H',
				'handOffDescription': 'Unassigned',
				'newHandOffDescription': '',
				'serviceUse': 'I',
				'newServiceUse': 'P',
				'serviceUseDescription': 'Itinerant',
				'newServiceUseDescription': '',
				'gmnInterfaceType': 'VIP',
				'newGMNInterfaceType': '',
				'detailedVIPFlows': [
					{
						'status': 'New',
						'flowNo': '1',
						'TxRx': 'TX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.TX1',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.TX1',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '2000',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '255.255.255.0',
						'customerGateway': '1.1.1.100',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '3000',
						'mediaFlowDestPort': '4000',
						'mediaFlowSsrc': 'ssrc',
						'mediaFlowProtocol': 'protocol',
						'mediaFlowHitlessMode': 'test',
						'mediaFlowMbps': '55'
					},
					{
						'status': 'New',
						'flowNo': '2',
						'TxRx': 'TX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.TX2',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.TX2',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '2000',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '255.255.255.0',
						'customerGateway': '1.1.1.100',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '3000',
						'mediaFlowDestPort': '4000',
						'mediaFlowSsrc': 'ssrc',
						'mediaFlowProtocol': 'protocol',
						'mediaFlowHitlessMode': 'test',
						'mediaFlowMbps': '55'
					},
					{
						'status': 'New',
						'flowNo': '3',
						'TxRx': 'TX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.TX3',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.TX3',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '4000',
						'customerVideoIp': '5.5.5.5',
						'customerNetmask': '5.5.5.55',
						'customerGateway': '5.5.5.6',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': '25'
					},
					{
						'status': 'New',
						'flowNo': '4',
						'TxRx': 'TX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.TX4',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.TX4',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '2000',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '255.255.255.0',
						'customerGateway': '1.1.1.100',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '3000',
						'mediaFlowDestPort': '4000',
						'mediaFlowSsrc': 'ssrc',
						'mediaFlowProtocol': 'protocol',
						'mediaFlowHitlessMode': 'test',
						'mediaFlowMbps': '55'
					},
					{
						'status': 'New',
						'flowNo': '5',
						'TxRx': 'TX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.TX5',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.TX5',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '2000',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '255.255.255.0',
						'customerGateway': '1.1.1.100',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '3000',
						'mediaFlowDestPort': '4000',
						'mediaFlowSsrc': 'ssrc',
						'mediaFlowProtocol': 'protocol',
						'mediaFlowHitlessMode': 'test',
						'mediaFlowMbps': '55'
					},
					{
						'status': 'New',
						'flowNo': '1',
						'TxRx': 'RX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.RX1',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.RX1',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '4000',
						'customerVideoIp': '5.5.5.5',
						'customerNetmask': '5.5.5.55',
						'customerGateway': '5.5.5.6',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': '25'
					},
					{
						'status': 'New',
						'flowNo': '2',
						'TxRx': 'RX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.RX2',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.RX2',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '2000',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '255.255.255.0',
						'customerGateway': '1.1.1.100',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '3000',
						'mediaFlowDestPort': '4000',
						'mediaFlowSsrc': 'ssrc',
						'mediaFlowProtocol': 'protocol',
						'mediaFlowHitlessMode': 'test',
						'mediaFlowMbps': '55'
					},
					{
						'status': 'New',
						'flowNo': '3',
						'TxRx': 'RX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.RX3',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.RX3',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '2000',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '255.255.255.0',
						'customerGateway': '1.1.1.100',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '3000',
						'mediaFlowDestPort': '4000',
						'mediaFlowSsrc': 'ssrc',
						'mediaFlowProtocol': 'protocol',
						'mediaFlowHitlessMode': 'test',
						'mediaFlowMbps': '55'
					},
					{
						'status': 'New',
						'flowNo': '4',
						'TxRx': 'RX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.RX4',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.RX4',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '4000',
						'customerVideoIp': '5.5.5.5',
						'customerNetmask': '5.5.5.55',
						'customerGateway': '5.5.5.6',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': '25'
					},
					{
						'status': 'New',
						'flowNo': '5',
						'TxRx': 'RX',
						'engineeringName': 'TGL-GDIH-A1105-1B.2.4.B.VIP.RX5',
						'friendlyName': 'TELSTRA BARRY AP VIP-1B.2.4.RX5',
						'serviceType': '',
						'requestType': '',
						'customerVlan': '4000',
						'customerVideoIp': '5.5.5.5',
						'customerNetmask': '5.5.5.55',
						'customerGateway': '5.5.5.6',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': '25'
					}
				]
			}
		],
		'createdAt': '2024-10-16T23:41:41.209Z',
		'updatedAt': '2024-10-16T23:41:41.209Z',
		'version': 0,
		'id': '67104f3571a284f98ede08db'
	},
	'projectNumber': 'TestProjectNumber001',
	'userName': 'Chinmaya Balakrishna',
	'createdAt': '2024-10-16T23:42:56.312Z',
	'updatedAt': '2024-10-16T23:43:05.334Z',
	'version': 2,
	'id': '67104f800b7a1170bc389b1d'
};

export const mockOrderData2 = {
	'issues': {
		'epicId': 'BMGMN-9196',
		'projectStoryId': 'BMGMN-9197',
		'designStoryId': 'BMGMN-9198',
		'networkStoryId': 'BMGMN-9199',
		'codecStoryId': 'BMGMN-9200'
	},
	'projectNumber': 'TestProjectNumber002',
	'userId': '6697d8c836bf4bae831e8bc8',
	'status': 'awaiting:feasibility',
	'expiresAt': '2025-01-24T23:42:56.311Z',
	'serviceOrder': {
		'userId': '6697d8c836bf4bae831e8bc8',
		'userName': 'Chinmaya Balakrishna',
		'status': 'confirmed',
		'network': 'G',
		'projectName': 'Resources Project Name 191',
		'remarks': 'Brief description about this order - Resources Project Name 191',
		'handoverDate': '31/Dec/2024',
		'supportingDocs': [
			{
				'path': '1 - FIFA WWC 23 - Media data.pdf',
				'preview': 'blob:https://portal.gmn.media.aws.cloud.in.company.com.au/7fd5d9af-f522-45f9-82ab-e3417757b015'
			}
		],
		'supportingExcels': [
			{
				'path': 'Laver Cup Berlin 2024 v2.1 3 services.xlsm',
				'preview': 'blob:https://portal.gmn.media.aws.cloud.in.company.com.au/94621bab-7b69-4eda-931f-9d0a77f78144'
			}
		],
		'orderType': 'MOT',
		'customerName': 'TGL',
		'cidn': '15768',
		'aSiteName': 'Core',
		'aEndAddress': 'Core',
		'currentStageCode': 'DSAL',
		'serviceType': 'HD',
		'country': 'AUS',
		'bSiteName': 'GDIH',
		'bEndAddress': 'BARRYST',
		'services': [
			{
				'sourceCountry': 'AUS',
				'sourceSite': 'GDIH',
				'sourceSiteDesc': 'BARRYST',
				'farCountry': '',
				'farSite': '',
				'farSiteDesc': '',
				'resource': 'Port',
				'requestType': 'newServiceToPort',
				'workRequired': 'VIP (NATFW)',
				'chassis': 'TGL-GDIH-A1105-1A',
				'path': 'A',
				'slot': 'MS 5',
				'slotId': '1752871',
				'slotName': 'TGL-GDIH-A1105-1A-MS 5',
				'card': 'SDMP-4S-Q40',
				'cardStatus': 'PLANNED',
				'newCardStatus': '701',
				'cardStatusDescription': 'Planned',
				'newCardStatusDescription': 'Planned',
				'cardProjectNumber': 'FY22BARRYST',
				'cardNewProjectNumber': '',
				'defaultApp': 'aperi-app-natfw-1g',
				'newDefaultApp': '',
				'cardHandOff': 'Unassigned',
				'newCardHandOff': '',
				'cardHandOffDescription': 'Unassigned',
				'newCardHandOffDescription': '',
				'pinOut': 'D',
				'newPinOut': '',
				'pinOutDescription': 'Data Centre Interconnect',
				'newPinOutDescription': '',
				'port': 'TGL-GDIH-A1105-1A.5.4.H.VIP',
				'portId': '801013',
				'portStatus': 'PLANNED',
				'newPortStatus': 'PLANNED',
				'portStatusDescription': 'Planned',
				'newPortStatusDescription': 'Planned',
				'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP',
				'friendlyName': 'BARRYST AP VIP-1A.5.4.H',
				'portNo': '7',
				'portProjectNumber': 'TestProjectNATFW02',
				'portNewProjectNumber': '',
				'TxFlows': '0',
				'RxFlows': '0',
				'vipBlock': '2',
				'newVIPBlock': '0',
				'serviceType': 'VIP (NATFW)',
				'newServiceType': 'VIP (NATFW)',
				'handOff': 'H',
				'newHandOff': '',
				'handOffDescription': 'Hitless',
				'newHandOffDescription': 'Non-Hitless',
				'serviceUse': 'I',
				'newServiceUse': 'P',
				'serviceUseDescription': 'Itinerant',
				'newServiceUseDescription': 'Permanent',
				'gmnInterfaceType': 'VIP',
				'newGMNInterfaceType': 'VIP',
				'detailedVIPFlows': [
					{
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX1',
						'status': 'Modified',
						'flowNo': '1',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX1',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX1',
						'primaryIp': '10.12.20.79',
						'primaryMulticastIp': '225.12.20.79',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.79',
						'secondaryMulticastIp': '225.212.21.79',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestingPorta2002',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'CHANGE',
						'customerVlan': '3100',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '1.1.1.12',
						'customerGateway': '1.1.1.15',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '2100',
						'mediaFlowDestPort': '2200',
						'mediaFlowSsrc': 'v3',
						'mediaFlowProtocol': 'TEST',
						'mediaFlowHitlessMode': 'Hitless',
						'mediaFlowMbps': '55'
					},
					{
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX2',
						'status': 'Modified',
						'flowNo': '2',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX2',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX2',
						'primaryIp': '10.12.20.80',
						'primaryMulticastIp': '225.12.20.80',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.80',
						'secondaryMulticastIp': '225.212.21.80',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestProjectNATFW02',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'CHANGE',
						'customerVlan': '3100',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '1.1.1.12',
						'customerGateway': '1.1.1.15',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '2100',
						'mediaFlowDestPort': '2200',
						'mediaFlowSsrc': 'v3',
						'mediaFlowProtocol': 'TEST',
						'mediaFlowHitlessMode': 'Hitless',
						'mediaFlowMbps': '55'
					},
					{
						'name': 'TGL-GDIH-A1105-1A.5.4.A.VIP.RX2',
						'status': 'Deleted',
						'flowNo': '2',
						'TxRx': 'RX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP.RX2',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.RX2',
						'primaryIp': '10.12.20.80',
						'primaryMulticastIp': '225.12.20.80',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.80',
						'secondaryMulticastIp': '225.212.21.80',
						'secondaryVlan': '29',
						'flowProjectNumber': 'Testing21Dec2023',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': '',
						'requestType': 'NEW',
						'customerVlan': '',
						'customerVideoIp': '',
						'customerNetmask': '',
						'customerGateway': '',
						'customerIgmpVersion': '',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': ''
					},
					{
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX3',
						'flowNo': '3',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX3',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX3',
						'primaryIp': '10.12.20.81',
						'primaryMulticastIp': '225.12.20.81',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.81',
						'secondaryMulticastIp': '225.212.21.81',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestProjectNATFW02',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'NEW',
						'customerVlan': '',
						'customerVideoIp': '',
						'customerNetmask': '',
						'customerGateway': '',
						'customerIgmpVersion': '',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': ''
					}
				]
			}
		],
		'createdAt': '2024-10-16T23:41:41.209Z',
		'updatedAt': '2024-10-16T23:41:41.209Z',
		'version': 0,
		'id': '67104f3571a284f98ede08db'
	},
	'userName': 'Chinmaya Balakrishna',
	'createdAt': '2024-10-16T23:42:56.312Z',
	'updatedAt': '2024-10-16T23:43:05.334Z',
	'version': 2,
	'id': '67104f800b7a1170bc389b12'
};

export const mockOrderData3 = {
	'issues': {
		'epicId': 'BMGMN-9196',
		'projectStoryId': 'BMGMN-9197',
		'designStoryId': 'BMGMN-9198',
		'networkStoryId': 'BMGMN-9199',
		'codecStoryId': 'BMGMN-9200'
	},
	'userId': '6697d8c836bf4bae831e8bc8',
	'status': 'awaiting:feasibility',
	'expiresAt': '2025-01-24T23:42:56.311Z',
	'projectNumber': 'TestProjectNumber003',
	'serviceOrder': {
		'userId': '6697d8c836bf4bae831e8bc8',
		'userName': 'Chinmaya Balakrishna',
		'status': 'confirmed',
		'network': 'G',
		'projectName': 'Resources Project Name 191',
		'remarks': 'Brief description about this order - Resources Project Name 191',
		'handoverDate': '31/Dec/2024',
		'supportingDocs': [
			{
				'path': '1 - FIFA WWC 23 - Media data.pdf',
				'preview': 'blob:https://portal.gmn.media.aws.cloud.in.company.com.au/7fd5d9af-f522-45f9-82ab-e3417757b015'
			}
		],
		'supportingExcels': [
			{
				'path': 'Laver Cup Berlin 2024 v2.1 3 services.xlsm',
				'preview': 'blob:https://portal.gmn.media.aws.cloud.in.company.com.au/94621bab-7b69-4eda-931f-9d0a77f78144'
			}
		],
		'orderType': 'MOT',
		'customerName': 'TGL',
		'cidn': '15768',
		'aSiteName': 'Core',
		'aEndAddress': 'Core',
		'currentStageCode': 'DSAL',
		'serviceType': 'HD',
		'country': 'AUS',
		'bSiteName': 'GDIH',
		'bEndAddress': 'BARRYST',
		'services': [
			{
				'sourceCountry': 'AUS',
				'sourceSite': 'GDIH',
				'sourceSiteDesc': 'BARRYST',
				'farCountry': '',
				'farSite': '',
				'farSiteDesc': '',
				'resource': 'Port',
				'requestType': 'newServiceToPort',
				'workRequired': 'VIP (NATFW)',
				'chassis': 'TGL-GDIH-A1105-1A',
				'path': 'A',
				'slot': 'MS 5',
				'slotId': '1752871',
				'slotName': 'TGL-GDIH-A1105-1A-MS 5',
				'card': 'SDMP-4S-Q40',
				'cardStatus': 'PLANNED',
				'newCardStatus': '701',
				'cardStatusDescription': 'Planned',
				'newCardStatusDescription': 'Planned',
				'cardProjectNumber': 'FY22BARRYST',
				'cardNewProjectNumber': '',
				'defaultApp': 'aperi-app-natfw-1g',
				'newDefaultApp': '',
				'cardHandOff': 'Unassigned',
				'newCardHandOff': '',
				'cardHandOffDescription': 'Unassigned',
				'newCardHandOffDescription': '',
				'pinOut': 'D',
				'newPinOut': '',
				'pinOutDescription': 'Data Centre Interconnect',
				'newPinOutDescription': '',
				'port': 'TGL-GDIH-A1105-1A.5.4.H.VIP',
				'portId': '801013',
				'portStatus': 'PLANNED',
				'newPortStatus': 'PLANNED',
				'portStatusDescription': 'Planned',
				'newPortStatusDescription': 'Planned',
				'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP',
				'friendlyName': 'BARRYST AP VIP-1A.5.4.H',
				'portNo': '7',
				'portProjectNumber': 'TestProjectNATFW02',
				'portNewProjectNumber': '',
				'TxFlows': '0',
				'RxFlows': '0',
				'vipBlock': '2',
				'newVIPBlock': '0',
				'serviceType': 'VIP (NATFW)',
				'newServiceType': 'VIP (NATFW)',
				'handOff': 'H',
				'newHandOff': 'H',
				'handOffDescription': 'Hitless',
				'newHandOffDescription': 'Hitless',
				'serviceUse': 'I',
				'newServiceUse': 'P',
				'serviceUseDescription': 'Itinerant',
				'newServiceUseDescription': 'Permanent',
				'gmnInterfaceType': 'VIP',
				'newGMNInterfaceType': 'VIP',
				'detailedVIPFlows': [
					{
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX1',
						'status': 'Modified',
						'flowNo': '1',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX1',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX1',
						'primaryIp': '10.12.20.79',
						'primaryMulticastIp': '225.12.20.79',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.79',
						'secondaryMulticastIp': '225.212.21.79',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestingPorta2002',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'CHANGE',
						'customerVlan': '3100',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '1.1.1.12',
						'customerGateway': '1.1.1.15',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '2100',
						'mediaFlowDestPort': '2200',
						'mediaFlowSsrc': 'v3',
						'mediaFlowProtocol': 'TEST',
						'mediaFlowHitlessMode': 'Hitless',
						'mediaFlowMbps': '55'
					},
					{
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX2',
						'status': 'Modified',
						'flowNo': '2',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX2',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX2',
						'primaryIp': '10.12.20.80',
						'primaryMulticastIp': '225.12.20.80',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.80',
						'secondaryMulticastIp': '225.212.21.80',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestProjectNATFW02',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'CHANGE',
						'customerVlan': '3100',
						'customerVideoIp': '1.1.1.1',
						'customerNetmask': '1.1.1.12',
						'customerGateway': '1.1.1.15',
						'customerIgmpVersion': 'v3',
						'mediaFlowSourceIp': '2.2.2.2',
						'mediaFlowDestIp': '3.3.3.3',
						'mediaFlowSourcePort': '2100',
						'mediaFlowDestPort': '2200',
						'mediaFlowSsrc': 'v3',
						'mediaFlowProtocol': 'TEST',
						'mediaFlowHitlessMode': 'Hitless',
						'mediaFlowMbps': '55'
					},
					{
						'name': 'TGL-GDIH-A1105-1A.5.4.A.VIP.RX2',
						'status': 'Deleted',
						'flowNo': '2',
						'TxRx': 'RX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP.RX2',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.RX2',
						'primaryIp': '10.12.20.80',
						'primaryMulticastIp': '225.12.20.80',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.80',
						'secondaryMulticastIp': '225.212.21.80',
						'secondaryVlan': '29',
						'flowProjectNumber': 'Testing21Dec2023',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': '',
						'requestType': 'NEW',
						'customerVlan': '',
						'customerVideoIp': '',
						'customerNetmask': '',
						'customerGateway': '',
						'customerIgmpVersion': '',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': ''
					},
					{
						'name': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX3',
						'flowNo': '3',
						'TxRx': 'TX',
						'mainPortEngineeringName': 'TGL-GDIH-A1105-1A.5.4.A.VIP',
						'engineeringName': 'TGL-GDIH-A1105-1A.5.4.H.VIP.TX3',
						'friendlyName': 'BARRYST AP VIP-1A.5.4.H.TX3',
						'primaryIp': '10.12.20.81',
						'primaryMulticastIp': '225.12.20.81',
						'primaryVlan': '19',
						'secondaryIp': '10.212.21.81',
						'secondaryMulticastIp': '225.212.21.81',
						'secondaryVlan': '29',
						'flowProjectNumber': 'TestProjectNATFW02',
						'flowStatus': 'PLANNED',
						'scheduallUpdated': 'N',
						'dataminerUpdated': 'N',
						'serviceType': 'H',
						'requestType': 'NEW',
						'customerVlan': '',
						'customerVideoIp': '',
						'customerNetmask': '',
						'customerGateway': '',
						'customerIgmpVersion': '',
						'mediaFlowSourceIp': '',
						'mediaFlowDestIp': '',
						'mediaFlowSourcePort': '',
						'mediaFlowDestPort': '',
						'mediaFlowSsrc': '',
						'mediaFlowProtocol': '',
						'mediaFlowHitlessMode': '',
						'mediaFlowMbps': ''
					}
				]
			}
		],
		'createdAt': '2024-10-16T23:41:41.209Z',
		'updatedAt': '2024-10-16T23:41:41.209Z',
		'version': 0,
		'id': '67104f3571a284f98ede08db'
	},
	'userName': 'Chinmaya Balakrishna',
	'createdAt': '2024-10-16T23:42:56.312Z',
	'updatedAt': '2024-10-16T23:43:05.334Z',
	'version': 2,
	'id': '67104f800b7a1170bc389b13'
};

export const mockOrderData4 = {
	'issues': {
		'epicId': 'BMGMN-9424',
		'projectStoryId': 'BMGMN-9425',
		'designStoryId': 'BMGMN-9426',
		'networkStoryId': 'BMGMN-9427',
		'codecStoryId': 'BMGMN-9428'
	},
	'userId': '658391d8bade494a7ee8c645',
	'status': 'design:ready',
	'expiresAt': '2025-02-28T00:17:28.900Z',
	'serviceOrder': {
		'userId': '658391d8bade494a7ee8c645',
		'userName': 'Miro Macapagal',
		'status': 'confirmed',
		'network': 'G',
		'projectName': 'Hitless Upgrade for USGR Encompass',
		'remarks': 'Email from Ali: \n\nHi GMN Team\n\nCan you please upgrade all the RX and TX ports at USGR ( Encompass) to support hitless? Attached is the MOT',
		'handoverDate': '29/Nov/2024',
		'supportingDocs': [{
			'path': 'MOT-USGR upgarde to Hitles -  v1.pdf',
			'preview': 'blob:https://portal.gmn.media.aws.cloud.in.company.com.au/e34e2d13-7053-4c44-9f67-e31505f37cfd'
		}],
		'supportingExcels': [{
			'path': '2024-11-19_MOT-USGR upgarde to Hitles -  v1.xlsm',
			'preview': 'blob:https://portal.gmn.media.aws.cloud.in.company.com.au/8811eeeb-d919-4ac4-95cd-f9046170dae5'
		}],
		'orderType': 'MOT',
		'customerName': 'TGL',
		'cidn': '15768',
		'aSiteName': 'Core',
		'aEndAddress': 'Core',
		'currentStageCode': 'DSAL',
		'serviceType': 'HD',
		'country': 'USA',
		'bSiteName': 'USGR',
		'bEndAddress': 'ENCNY',
		'services': [{
			'sourceCountry': 'USA',
			'sourceSite': 'USGR',
			'sourceSiteDesc': 'ENCNY',
			'farCountry': '',
			'farSite': '',
			'farSiteDesc': '',
			'resource': 'Card',
			'requestType': 'newServiceToCard',
			'workRequired': 'aperi-app-s22-127',
			'chassis': 'TGL-USGR-A1105-1A',
			'path': 'A',
			'slot': 'MS 1',
			'slotId': '1746733',
			'slotName': 'TGL-USGR-A1105-1A-MS 1',
			'card': 'SDMP-4S-Q40',
			'cardStatus': 'ACCEPTED',
			'newCardStatus': '701',
			'cardStatusDescription': 'Accepted',
			'newCardStatusDescription': 'Planned',
			'cardProjectNumber': 'Unassigned',
			'cardNewProjectNumber': '',
			'defaultApp': 'Unassigned',
			'newDefaultApp': 'aperi-app-s22-127',
			'cardHandOff': 'Unassigned',
			'newCardHandOff': 'H',
			'cardHandOffDescription': 'Unassigned',
			'newCardHandOffDescription': '',
			'pinOut': 'Unassigned',
			'newPinOut': 'V',
			'pinOutDescription': 'Unassigned',
			'newPinOutDescription': '',
			'port': '',
			'portId': '',
			'portStatus': '',
			'newPortStatus': 'PLANNED',
			'portStatusDescription': '',
			'newPortStatusDescription': 'Planned',
			'engineeringName': '',
			'friendlyName': '',
			'portNo': '',
			'portProjectNumber': '',
			'portNewProjectNumber': '',
			'TxFlows': '0',
			'RxFlows': '0',
			'vipBlock': '0',
			'newVIPBlock': '0',
			'serviceType': '',
			'newServiceType': '',
			'handOff': '',
			'newHandOff': '',
			'handOffDescription': '',
			'newHandOffDescription': '',
			'serviceUse': '',
			'newServiceUse': '',
			'serviceUseDescription': '',
			'newServiceUseDescription': '',
			'gmnInterfaceType': '',
			'newGMNInterfaceType': '',
			'detailedVIPFlows': []
		}, {
			'sourceCountry': 'USA',
			'sourceSite': 'USGR',
			'sourceSiteDesc': 'ENCNY',
			'farCountry': '',
			'farSite': '',
			'farSiteDesc': '',
			'resource': 'Card',
			'requestType': 'newServiceToCard',
			'workRequired': 'aperi-app-s22-127',
			'chassis': 'TGL-USGR-A1105-1A',
			'path': 'A',
			'slot': 'MS 2',
			'slotId': '1746734',
			'slotName': 'TGL-USGR-A1105-1A-MS 2',
			'card': 'SDMP-4S-Q40',
			'cardStatus': 'ACCEPTED',
			'newCardStatus': '701',
			'cardStatusDescription': 'Accepted',
			'newCardStatusDescription': 'Planned',
			'cardProjectNumber': 'Unassigned',
			'cardNewProjectNumber': '',
			'defaultApp': 'Unassigned',
			'newDefaultApp': 'aperi-app-s22-127',
			'cardHandOff': 'Unassigned',
			'newCardHandOff': 'H',
			'cardHandOffDescription': 'Unassigned',
			'newCardHandOffDescription': '',
			'pinOut': 'Unassigned',
			'newPinOut': 'V',
			'pinOutDescription': 'Unassigned',
			'newPinOutDescription': '',
			'port': '',
			'portId': '',
			'portStatus': '',
			'newPortStatus': 'PLANNED',
			'portStatusDescription': '',
			'newPortStatusDescription': 'Planned',
			'engineeringName': '',
			'friendlyName': '',
			'portNo': '',
			'portProjectNumber': '',
			'portNewProjectNumber': '',
			'TxFlows': '0',
			'RxFlows': '0',
			'vipBlock': '0',
			'newVIPBlock': '0',
			'serviceType': '',
			'newServiceType': '',
			'handOff': '',
			'newHandOff': '',
			'handOffDescription': '',
			'newHandOffDescription': '',
			'serviceUse': '',
			'newServiceUse': '',
			'serviceUseDescription': '',
			'newServiceUseDescription': '',
			'gmnInterfaceType': '',
			'newGMNInterfaceType': '',
			'detailedVIPFlows': []
		}, {
			'sourceCountry': 'USA',
			'sourceSite': 'USGR',
			'sourceSiteDesc': 'ENCNY',
			'farCountry': '',
			'farSite': '',
			'farSiteDesc': '',
			'resource': 'Card',
			'requestType': 'newServiceToCard',
			'workRequired': 'aperi-app-s22-127',
			'chassis': 'TGL-USGR-A1105-1A',
			'path': 'A',
			'slot': 'MS 3',
			'slotId': '1746735',
			'slotName': 'TGL-USGR-A1105-1A-MS 3',
			'card': 'SDMP-4S-Q40',
			'cardStatus': 'ACCEPTED',
			'newCardStatus': '701',
			'cardStatusDescription': 'Accepted',
			'newCardStatusDescription': 'Planned',
			'cardProjectNumber': 'Unassigned',
			'cardNewProjectNumber': '',
			'defaultApp': 'Unassigned',
			'newDefaultApp': 'aperi-app-s22-127',
			'cardHandOff': 'Unassigned',
			'newCardHandOff': 'H',
			'cardHandOffDescription': 'Unassigned',
			'newCardHandOffDescription': '',
			'pinOut': 'Unassigned',
			'newPinOut': 'V',
			'pinOutDescription': 'Unassigned',
			'newPinOutDescription': '',
			'port': '',
			'portId': '',
			'portStatus': '',
			'newPortStatus': 'PLANNED',
			'portStatusDescription': '',
			'newPortStatusDescription': 'Planned',
			'engineeringName': '',
			'friendlyName': '',
			'portNo': '',
			'portProjectNumber': '',
			'portNewProjectNumber': '',
			'TxFlows': '0',
			'RxFlows': '0',
			'vipBlock': '0',
			'newVIPBlock': '0',
			'serviceType': '',
			'newServiceType': '',
			'handOff': '',
			'newHandOff': '',
			'handOffDescription': '',
			'newHandOffDescription': '',
			'serviceUse': '',
			'newServiceUse': '',
			'serviceUseDescription': '',
			'newServiceUseDescription': '',
			'gmnInterfaceType': '',
			'newGMNInterfaceType': '',
			'detailedVIPFlows': []
		}, {
			'sourceCountry': 'USA',
			'sourceSite': 'USGR',
			'sourceSiteDesc': 'ENCNY',
			'farCountry': '',
			'farSite': '',
			'farSiteDesc': '',
			'resource': 'Card',
			'requestType': 'newServiceToCard',
			'workRequired': 'aperi-app-s22-127',
			'chassis': 'TGL-USGR-A1105-1B',
			'path': 'B',
			'slot': 'MS 1',
			'slotId': '1748067',
			'slotName': 'TGL-USGR-A1105-1B-MS 1',
			'card': 'SDMP-4S-Q40',
			'cardStatus': 'ACCEPTED',
			'newCardStatus': '701',
			'cardStatusDescription': 'Accepted',
			'newCardStatusDescription': 'Planned',
			'cardProjectNumber': 'Unassigned',
			'cardNewProjectNumber': '',
			'defaultApp': 'Unassigned',
			'newDefaultApp': 'aperi-app-s22-127',
			'cardHandOff': 'Unassigned',
			'newCardHandOff': 'H',
			'cardHandOffDescription': 'Unassigned',
			'newCardHandOffDescription': '',
			'pinOut': 'Unassigned',
			'newPinOut': 'V',
			'pinOutDescription': 'Unassigned',
			'newPinOutDescription': '',
			'port': '',
			'portId': '',
			'portStatus': '',
			'newPortStatus': 'PLANNED',
			'portStatusDescription': '',
			'newPortStatusDescription': 'Planned',
			'engineeringName': '',
			'friendlyName': '',
			'portNo': '',
			'portProjectNumber': '',
			'portNewProjectNumber': '',
			'TxFlows': '0',
			'RxFlows': '0',
			'vipBlock': '0',
			'newVIPBlock': '0',
			'serviceType': '',
			'newServiceType': '',
			'handOff': '',
			'newHandOff': '',
			'handOffDescription': '',
			'newHandOffDescription': '',
			'serviceUse': '',
			'newServiceUse': '',
			'serviceUseDescription': '',
			'newServiceUseDescription': '',
			'gmnInterfaceType': '',
			'newGMNInterfaceType': '',
			'detailedVIPFlows': []
		}, {
			'sourceCountry': 'USA',
			'sourceSite': 'USGR',
			'sourceSiteDesc': 'ENCNY',
			'farCountry': '',
			'farSite': '',
			'farSiteDesc': '',
			'resource': 'Card',
			'requestType': 'newServiceToCard',
			'workRequired': 'aperi-app-s22-127',
			'chassis': 'TGL-USGR-A1105-1B',
			'path': 'B',
			'slot': 'MS 2',
			'slotId': '1748068',
			'slotName': 'TGL-USGR-A1105-1B-MS 2',
			'card': 'SDMP-4S-Q40',
			'cardStatus': 'ACCEPTED',
			'newCardStatus': '701',
			'cardStatusDescription': 'Accepted',
			'newCardStatusDescription': 'Planned',
			'cardProjectNumber': 'Unassigned',
			'cardNewProjectNumber': '',
			'defaultApp': 'Unassigned',
			'newDefaultApp': 'aperi-app-s22-127',
			'cardHandOff': 'Unassigned',
			'newCardHandOff': 'H',
			'cardHandOffDescription': 'Unassigned',
			'newCardHandOffDescription': '',
			'pinOut': 'Unassigned',
			'newPinOut': 'V',
			'pinOutDescription': 'Unassigned',
			'newPinOutDescription': '',
			'port': '',
			'portId': '',
			'portStatus': '',
			'newPortStatus': 'PLANNED',
			'portStatusDescription': '',
			'newPortStatusDescription': 'Planned',
			'engineeringName': '',
			'friendlyName': '',
			'portNo': '',
			'portProjectNumber': '',
			'portNewProjectNumber': '',
			'TxFlows': '0',
			'RxFlows': '0',
			'vipBlock': '0',
			'newVIPBlock': '0',
			'serviceType': '',
			'newServiceType': '',
			'handOff': '',
			'newHandOff': '',
			'handOffDescription': '',
			'newHandOffDescription': '',
			'serviceUse': '',
			'newServiceUse': '',
			'serviceUseDescription': '',
			'newServiceUseDescription': '',
			'gmnInterfaceType': '',
			'newGMNInterfaceType': '',
			'detailedVIPFlows': []
		}, {
			'sourceCountry': 'USA',
			'sourceSite': 'USGR',
			'sourceSiteDesc': 'ENCNY',
			'farCountry': '',
			'farSite': '',
			'farSiteDesc': '',
			'resource': 'Card',
			'requestType': 'newServiceToCard',
			'workRequired': 'aperi-app-s22-127',
			'chassis': 'TGL-USGR-A1105-1B',
			'path': 'B',
			'slot': 'MS 3',
			'slotId': '1748069',
			'slotName': 'TGL-USGR-A1105-1B-MS 3',
			'card': 'SDMP-4S-Q40',
			'cardStatus': 'ACCEPTED',
			'newCardStatus': '701',
			'cardStatusDescription': 'Accepted',
			'newCardStatusDescription': 'Planned',
			'cardProjectNumber': 'Unassigned',
			'cardNewProjectNumber': '',
			'defaultApp': 'Unassigned',
			'newDefaultApp': 'aperi-app-s22-127',
			'cardHandOff': 'Unassigned',
			'newCardHandOff': 'H',
			'cardHandOffDescription': 'Unassigned',
			'newCardHandOffDescription': '',
			'pinOut': 'Unassigned',
			'newPinOut': 'V',
			'pinOutDescription': 'Unassigned',
			'newPinOutDescription': '',
			'port': '',
			'portId': '',
			'portStatus': '',
			'newPortStatus': 'PLANNED',
			'portStatusDescription': '',
			'newPortStatusDescription': 'Planned',
			'engineeringName': '',
			'friendlyName': '',
			'portNo': '',
			'portProjectNumber': '',
			'portNewProjectNumber': '',
			'TxFlows': '0',
			'RxFlows': '0',
			'vipBlock': '0',
			'newVIPBlock': '0',
			'serviceType': '',
			'newServiceType': '',
			'handOff': '',
			'newHandOff': '',
			'handOffDescription': '',
			'newHandOffDescription': '',
			'serviceUse': '',
			'newServiceUse': '',
			'serviceUseDescription': '',
			'newServiceUseDescription': '',
			'gmnInterfaceType': '',
			'newGMNInterfaceType': '',
			'detailedVIPFlows': []
		}],
		'createdAt': '2024-11-20T00:17:20.345Z',
		'updatedAt': '2024-11-20T00:17:20.345Z',
		'version': 0,
		'id': '673d2a903cba5b7c488ed7bd'
	},
	'userName': 'Miro Macapagal',
	'createdAt': '2024-11-20T00:17:28.901Z',
	'updatedAt': '2025-02-10T07:57:39.885Z',
	'version': 19,
	'projectNumber': 'FY25M27ENCOMPASSHUGMB14',
	'id': '673d2a98005daf3c34c22ae6'
};

module.exports = {mockOrderData1, mockOrderData2, mockOrderData3, mockOrderData4};